log_level: INFO
log_file_path: data/monitoring.log
database_path: data/website_monitor.db
default_monitoring_interval_hours: 1
default_monitoring_interval_minutes: 60
website_list_storage_type: json
website_list_file_path: data/websites.json
snapshot_directory: data/snapshots
playwright_browser_type: chromium
playwright_headless_mode: true
playwright_user_agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36
  (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36
playwright_render_delay_ms: 3000
playwright_navigation_timeout_ms: 60000
notification_email_from: support@westlanddre.com
notification_email_to: sarmadsahib786@gmail.com
dashboard_url: ${DASHBOARD_URL:-https://websitemonitor.digitalclics.com}
content_change_threshold: 100.0
image_diff_threshold: 1000
structure_change_threshold: 100.0
semantic_similarity_threshold: 0.9
ssim_similarity_threshold: 0.95
visual_change_alert_threshold_percent: 0.01
meta_tags_to_check:
- title
- description
visual_comparison_ignore_regions: null
check_history_file_path: data/check_history.json
fetch_retry_total: 3
fetch_retry_backoff_factor: 0.3
fetch_retry_status_forcelist:
- 500
- 502
- 503
- 504
dashboard_port: 5001
log_level_dashboard: INFO
log_file_dashboard: data/dashboard.log
dashboard_history_limit: 20
dashboard_api_history_limit: 100
smtp_server: 
smtp_port: 587
smtp_username: 
smtp_password: 
smtp_use_tls: true
smtp_use_ssl: false
default_notification_email: websitecheckapp@digitalclics.com
crawler_max_depth: 2
crawler_respect_robots: true
crawler_check_external_links: true
crawler_user_agent: SiteMonitor Bot
greenflare_timeout: 30
greenflare_retries: 3
greenflare_backoff_base: 2
greenflare_extract_images: true
greenflare_extract_alt_text: true
greenflare_extract_meta_tags:
- title
- description
- keywords
- og:title
- og:description
- twitter:title
- twitter:description
playwright_retries: 2
snapshot_format: png
monitoring_interval_seconds: 300
enable_scheduler: true
blur_detection_threshold: 85
blur_detection_percentage_threshold: 15
blur_detection_min_image_size: 100
blur_detection_timeout: 30
blur_detection_resize_dimensions:
- 1280
- 720
blur_detection_cleanup_days: 30
blur_detection_email_template: 'Subject: Blurry Images Detected - {website_name}


  Dear Administrator,


  Our website monitoring system has detected {blurry_count} blurry images on {website_name}.


  Details:

  - Total images analyzed: {total_images}

  - Blurry images found: {blurry_count}

  - Average blur score: {avg_blur_score}


  Please review the images in your dashboard for more details.


  Best regards,

  Website Monitoring System

  '
visual_difference_threshold: 5.0
google_pagespeed_api_key: AIzaSyBalq6kgTjMTDlulVWnJ69Pu8mT3sZ_kZU
scheduler_enabled: true
scheduler_startup_delay_seconds: 10
scheduler_check_interval_seconds: 60
# Exclude pages configuration - pages containing these keywords will be skipped for visual, blur, and baseline checks
exclude_pages_keywords:
- "products"
- "blogs"
- "blog"
- "product"
- "shop"
- "store"
- "cart"
- "checkout"
- "account"
- "login"
- "register"
- "search"
- "category"
- "tag"
- "archive"
# Maximum concurrent site checks (reduced for better performance)
max_concurrent_site_checks: 1

# SINGLE-SITE PROCESSING CONFIGURATION
single_site_processing:
  enabled: true
  request_delay_seconds: 2  # Delay between requests to same site
  check_delay_seconds: 5    # Delay between different check types
  retry_attempts: 3         # Number of retry attempts on failure
  retry_delay_seconds: 10   # Delay between retries
  cleanup_delay_seconds: 2  # Delay for cleanup between sites

# WEBSOCKET CONFIGURATION
websocket:
  host: localhost
  port: 8765
  enabled: true